echo Building mongodb...
./mongo.build.sh

echo Building jitserver...
./jitserver.build.sh

echo Building acmeair containers...
./acmeair.build.sh

echo Building jmeter containers...
./jmeter.build.sh
